### ISSUE TITLE
Create Components For Functionality

### ISSUE THREAD

**Issue by AshlavaDev** [AshlavaDev/mini-painter-library#10]
## Objective

Components are created for basic website features (eg navbar)

## Definition of Done

All components needed to make a basic website are done

## Tasks

- [x] Component files are created
- [x] Functionality of components exists and is correct
- [x] Components are applied to correct parents
