### ISSUE TITLE
Unify Styling

### ISSUE THREAD

**Issue by AshlavaDev** [AshlavaDev/mini-painter-library#11]
## Objective

Website looks as it should

## Definition of Done

Website is styled correctly for all components and pages with no disparities

## Tasks

- [x] Import TailwindCSS
- [ ] Apply consistent styles
- [ ] Ensure both mobile and desktop styled exist
- [ ] Ensure accessibility issues do not exist
