### ISSUE TITLE
Fill Database with Basic Data

### ISSUE THREAD

**Issue by AshlavaDev** [AshlavaDev/mini-painter-library#2]
## Objective

Have enough data to show a working model of website

## Definition of Done

All require data is in database

## Tasks

- [x] Data source is found
- [x] Data is stored in csv files
- [x] Data is put into the backend
