### ISSUE TITLE
Finish Moodboard

### ISSUE THREAD

**Issue by AshlavaDev** [AshlavaDev/mini-painter-library#4]
## Objective

Have a moodboard to help with design of website

## Definition of Done

Moodboard has colour palettes, font examples, and screenshots of other websites for ideas

## Tasks

- [x] Colour palettes exist in moodboard
- [x] Font examples exist in moodboard
- [x] Website examples exist in moodboard
- [ ] (Optional) explanations exist in moodboard about items

**Comment by AshlavaDev** [comment]
Everything finished for moodboard
