### ISSUE TITLE
Learn React For Project

### ISSUE THREAD

**Issue by AshlavaDev** [AshlavaDev/mini-painter-library#5]
## Objective

Learn React

## Definition of Done

I know enough React to finish the website

## Tasks

- [x] Watch YouTube videos (Net Ninja being a good example)
- [x] Finish FreeCodeCamp React course
- [x] Build basic projects with React
