### ISSUE TITLE
Create Paint Cards

### ISSUE THREAD

**Issue by AshlavaDev** [AshlavaDev/mini-painter-library#8]
## Objective

Have a card component to insert paint information from database

## Definition of Done

Card is formatted and styled, and contains correct information

## Tasks

- [x] Create card component
- [x] Give card ability to be given information
- [x] Style card for both mobile and desktop sizes
