### ISSUE TITLE
Create Paint List

### ISSUE THREAD

**Issue by AshlavaDev** [AshlavaDev/mini-painter-library#9]
## Objective

Render one or more cards are rendered as a list

## Definition of Done

Cards are properly rendered based on input

## Tasks

- [x] Set up basic list component
- [x] Accept data from user
- [x] Pull information from user
- [x] Show correct information to user
